version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn stamp_assist.wsgi:application --bind 0.0.0.0:8100
    volumes:
      - stamp_assist_static_files:/app/staticfiles
    ports:
      - '8100:8100'
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - stamp_assist_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_NAME}
      - POSTGRES_HOST=${PG_HOST}
      - POSTGRES_PORT=${PG_PORT}

volumes:
  stamp_assist_postgres_data:
