# Generated by Django 4.2.1 on 2023-05-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_value',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='stamps_count',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='user',
            name='target_value',
            field=models.DecimalField(decimal_places=2, default=75, max_digits=10),
        ),
    ]
