# Generated by Django 4.2.1 on 2023-07-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_max_value_user_stamps_count_user_target_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_stamp_repeat',
            field=models.BooleanField(default=False),
        ),
    ]
