# Generated by Django 4.2.1 on 2024-01-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stamps_max',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='user',
            name='stamps_min',
            field=models.IntegerField(default=1),
        ),
    ]
