# Generated by Django 4.2.1 on 2024-01-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_stamps_max_user_stamps_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stamps_count',
        ),
    ]
