# Generated by Django 4.2.1 on 2023-05-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combinations', '0005_stampsample_userstamp_remove_stamp_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stampsample',
            name='image',
            field=models.ImageField(null=True, upload_to='upload/'),
        ),
    ]
