# Generated by Django 4.2.1 on 2023-05-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combinations', '0006_stampsample_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stampsample',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
