# Generated by Django 4.2.1 on 2023-06-28 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combinations', '0008_alter_userstamp_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstamp',
            name='quantity',
        ),
    ]
