# Generated by Django 4.2.1 on 2023-06-28 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combinations', '0009_remove_userstamp_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userstamp',
            unique_together=set(),
        ),
    ]
