# Generated by Django 4.2.1 on 2023-06-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combinations', '0010_alter_userstamp_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='desk',
            name='type',
            field=models.CharField(choices=[('available', 'Available'), ('postcard', 'Postcard')], default='available', max_length=100),
            preserve_default=False,
        ),
    ]
