# Generated by Django 4.2.1 on 2023-06-30 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('combinations', '0014_rename_user_name_userstamp_custom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstamp',
            name='desk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stamps', to='combinations.desk'),
        ),
    ]
