# Generated by Django 4.2.1 on 2023-07-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combinations', '0015_alter_userstamp_desk'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstamp',
            name='allow_repeat',
            field=models.BooleanField(default=False),
        ),
    ]
