# Generated by Django 4.2.1 on 2023-07-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combinations', '0017_alter_userstamp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stampsample',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='desk',
            name='type',
            field=models.CharField(choices=[('available', 'Available'), ('postcard', 'Postcard'), ('removed', 'Removed')], max_length=100),
        ),
    ]
