# Generated by Django 4.2.1 on 2023-07-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combinations', '0019_stampsample_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stampsample',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
