# Generated by Django 4.2.1 on 2024-01-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combinations', '0020_alter_stampsample_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stampsample',
            name='url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
